# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeb21e6996e42739012364816af9e69f1b2f8bcdfd3e6f7d6a5f8349296e9835e66b171eed8f9893645bd6c08af216d2215af63c53806a7435c9476384cf64a0

test:
  secret_key_base: c1297cf49eb87145e705f639914095cb20a8cc3b2c93d2a436ac8208aa3693afe45ad57abbb628d5d45fb8429fb65fda0e8c83f8d590ef2b188f834c093bbd2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
